### PR TITLE
Update to swift 4

### PR DESCRIPTION
**Pull request by kangaroo5383**
Best lib I was able to find and wanted to be using it in xcode-beta, since I was using it on my fork I figured I'll send in the PR 🎉

### CODE REVIEW

**Comment by timbueno** [comment]
+1

**Comment by soffes** [comment]
Does this still work with the current release of Xcode?

**Comment by kangaroo5383** [comment]
Yep seems to be, have been using the 9 beta 5 since yesterday and it's building fine.

**Comment by TomLiu** [comment]
Any progress? @soffes

**Comment by domdop** [comment]
@soffes could you merge it please

**Comment by ghost** [comment]
+1

**Pull request merged**
